export const SEARCHBOX_ACTION_TYPE = {
    SEARCH_INPUT_CHANGED: 'searchbar/SEARCH_INPUT_CHANGED',
    SEARCH_RESULTS_RECEIVED: 'searchbar/SEARCH_RESULTS_RECEIVED',
    SEARCH_RESULTS_CLEARED: 'searchbar/SEARCH_RESULTS_CLEARED',
}

